galaxy_info:
  author: Behnam Saberi
  description: A practice for launching a mysql cluster by ansible on docker 
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9
  galaxy_tags: []
dependencies: []
