# Install dependencies 
- name: install dependency
  become: yes
  become_user: root
  apt:
    name: "{{item}}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - python3-setuptools

# Add docker GPG
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add docker repository
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

# install Docker-ce and start the service
- name: Update apt and install docker-ce
  apt:  name=docker-ce state=latest

# Install docker module 
- name: Install Docker Module for Python
  pip:
    name: docker

# Create a bridge network 
- name: Create a network
  docker_network:
    name: mynet
    driver: bridge
